[tool.poetry]
name = "solid"
version = "0.1.0"
description = ""
authors = ["vitaliwow <varabyeu.v@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
typing-extensions = "^4.12.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
